# Generated by Django 5.0.3 on 2024-04-01 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0006_remove_pharmacist_opening_hours_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicineOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('medicine_description', models.TextField(blank=True, null=True)),
                ('medicine_description_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('order_description', models.TextField(blank=True, null=True)),
                ('order_location', models.CharField(max_length=100)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_order', to='accounts.client')),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pharmacist_order', to='accounts.pharmacist')),
            ],
        ),
    ]
