# Generated by Django 5.0.3 on 2024-03-23 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='appointment_duration',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='doctor',
            name='service_charge',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
