# Generated by Django 5.0.3 on 2024-03-23 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_doctor_appointment_duration_doctor_service_charge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='appointment_duration',
            field=models.IntegerField(choices=[(10, 10), (20, 20), (30, 30), (40, 40), (50, 50), (60, 60)], default=30),
        ),
    ]
