# Generated by Django 5.0.3 on 2024-03-25 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_doctor_appointment_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseuser',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='baseuser',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
