# Generated by Django 5.0.3 on 2024-03-25 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_baseuser_is_email_verified_baseuser_otp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='region_of_service',
            new_name='clinic_location',
        ),
    ]
