# Generated by Django 5.0.3 on 2024-03-28 06:01

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_region_of_service_doctor_clinic_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pharmacist',
            name='opening_hours',
        ),
        migrations.AddField(
            model_name='pharmacist',
            name='closing_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pharmacist',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pharmacist',
            name='opening_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pharmacist',
            name='pharmacy_location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pharmacist',
            name='delivery_service',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='pharmacist',
            name='pharmacy_license',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.license_image_path),
        ),
    ]
